In [314]:
import math
import random
import numpy as np

# Task 1


## Complete tasks, using
* NumPy functions
* iterative constructions (cycles, lists inclusions etc.)

### variant 6 tasks: 1, 3, 4, 6, 10, 12, 15, 17, 18

## 1:


##### Enter number n, generate n x n array of structure  
```
5  
[[1 0 0 0 0]  
 [0 2 0 0 0]  
 [0 0 3 0 0]  
 [0 0 0 4 0]  
 [0 0 0 0 5]]  
```
 with numbers from 1 to n on main diagonal.

In [315]:
def task_1_numpy(n):
    matrix = np.zeros((n, n))
    np.fill_diagonal(matrix, np.arange(1, n+1))
    return matrix

def task_1_iterative(n):
    return [[i if i == j else 0 for j in range(1, n+1)] for i in range(1, n+1)]

print(np.array_equal(task_1_numpy(3), [[1, 0, 0],
                                       [0, 2, 0],
                                       [0, 0, 3]]))

print(np.array_equal(task_1_numpy(10), task_1_iterative(10)))

%timeit -n 100 -r 10 task_1_numpy(100)
%timeit -n 100 -r 10 task_1_iterative(100)

True
True
6.68 µs ± 2.56 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
328 µs ± 11.6 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 3:


##### 4 numbers for input: n, m, r, c. Return array with size n×m, where each row with number r and each column with number c contain 0, other elements are 1.
```
6 7 2 3  
[[0 0 0 0 0 0 0]  
 [0 1 1 0 1 1 0]  
 [0 0 0 0 0 0 0]  
 [0 1 1 0 1 1 0]  
 [0 0 0 0 0 0 0]  
 [0 1 1 0 1 1 0]]  
```

In [316]:
def task_3_numpy(n, m, r, c):
    res = np.ones((n, m), dtype=int)
    res[::r] = 0
    res[:, ::c] = 0 
    return res

def task_3_iterative(n, m, r, c):
    return [[1 if i%r and j%c else 0 for j in range(0, m)] for i in range(0, n)]

print(task_3_numpy(6, 7, 2, 3))
print(np.array_equal(task_3_numpy(200, 300, 4, 5), task_3_iterative(200, 300, 4, 5)))

%timeit -n 100 -r 10 task_3_numpy(200, 300, 4, 5)
%timeit -n 100 -r 10 task_3_iterative(200, 300, 4, 5)

[[0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]
 [0 0 0 0 0 0 0]
 [0 1 1 0 1 1 0]]
True
11.3 µs ± 716 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
2.87 ms ± 111 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 4:


##### Numbers n і m on input. Return array of size n×m, where first row is array [0, .., m-1] and other elements are 0
```
3 4  
[[0 1 2 3]
 [0 0 0 0]  
 [0 0 0 0]]
```

In [317]:
def task_4_numpy(n, m):
    res = np.zeros((n, m), dtype=int)
    res[0] = np.arange(m, dtype=int)
    return res

def task_4_iterative(n, m):
    res = [[0] * m] * n
    res[0] = [i for i in range(m)]
    return res

print(task_4_numpy(3, 4))
print(np.array_equal(task_4_numpy(200, 300), task_4_iterative(200, 300)))

%timeit -n 100 -r 10 task_4_numpy(200, 300)
%timeit -n 100 -r 10 task_4_iterative(200, 300)

[[0 1 2 3]
 [0 0 0 0]
 [0 0 0 0]]
True
5.09 µs ± 900 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
8.33 µs ± 248 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 6:


##### Enter array, change all non-zero elements to -1  
3 4 0 9 7 0 6 0 4 0 3  
[-1 -1 0 -1 -1 0 -1 0 -1 0 -1]

In [318]:

def task_6_numpy(array):
    arr = np.array(array)
    arr[arr != 0] = -1
    return arr
    
def task_6_iterative(array):
    for i in range(len(array)):
        if array[i] != 0:
            array[i] = -1
    return array

arr = np.arange(-100, 100)

print(np.array_equal(task_6_numpy([1,0,2,0,3,0]), [-1,0,-1,0,-1,0]))
print(np.array_equal(task_6_numpy(arr), task_6_iterative(arr)))

%timeit -n 100 -r 10 task_6_numpy(arr)
%timeit -n 100 -r 10 task_6_iterative(arr)

True
True
2.15 µs ± 372 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
26.8 µs ± 2.98 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 10:


##### Enter numbers n and m, create array of random values n x m and calculate min, max, mean and standard deviation, round to 3 decimal digits   
    
4 5  
min: 0.038  
max: 0.946  
mean: 0.593  
standard deviation: 0.302

In [319]:
def task_10_numpy(n, m):
    matrix = np.random.random((n, m))
    minimum = np.min(matrix).round(3)
    maximum = np.max(matrix).round(3)
    mean = np.mean(matrix).round(3)
    std_dev = np.std(matrix).round(3)
    return minimum, maximum, mean, std_dev


def task_10_iterative(n, m):
    matrix = [[random.uniform(0, 1) for j in range(m)] for i in range(n)]
    
    minimum, maximum, mean = 1, 0, 0
    
    for i in range(n):
        for j in range(m):
            minimum = min(matrix[i][j], minimum)
            maximum = max(matrix[i][j], maximum)
            mean += matrix[i][j] / (n * m)
    
    std_dev = 0
    for i in range(n):
        for j in range(m):
            std_dev += ((matrix[i][j] - mean) ** 2) / (n * m)
    std_dev = math.sqrt(std_dev)
        
    return round(minimum, 3), round(maximum, 3), round(mean, 3), round(std_dev, 3)

%timeit -n 100 -r 10 task_10_numpy(100, 100)
%timeit -n 100 -r 10 task_10_iterative(100, 100)


99.6 µs ± 13.2 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
5.84 ms ± 186 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 12:


##### Create n x n array of ones and fill border with zeros  
```
4  
[[0 0 0 0]  
 [0 1 1 0]  
 [0 1 1 0]   
 [0 0 0 0]]
```

In [320]:
def task_12_numpy(n):
    matrix = np.ones((n, n), dtype=int)
    matrix[[0, n-1]] = matrix[1:n-1, [0, n-1]] = 0
    return matrix

def task_12_iterative(n):
    return [[1 if i>0 and i<n-1 and j>0 and j<n-1 else 0 for i in range(n)] for j in range(n)]

print(task_12_numpy(4))
print(np.array_equal(task_12_numpy(25), task_12_iterative(25)))

%timeit -n 100 -r 10 task_12_numpy(100)
%timeit -n 100 -r 10 task_12_iterative(100)

[[0 0 0 0]
 [0 1 1 0]
 [0 1 1 0]
 [0 0 0 0]]
True
8.51 µs ± 1.32 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
751 µs ± 30.1 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


In [321]:
%%timeit -n 100 -r 10
# Iterative
def task_11(n):
    matrix = [[1 for j in range(n)] for i in range(n)]

    matrix.insert(0, [0 for j in range(n)])
    matrix.append([0 for j in range(n)])
    
    for i in range(n + 2):
        matrix[i].insert(0, 0)
        matrix[i].append(0)
        
    return matrix
    
task_11(100)

211 µs ± 10.4 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 15:


##### Fill even columns of n x n array with with ones and odd columns with zeros  
```
5  
[[0 1 0 1 0]  
 [0 1 0 1 0]  
 [0 1 0 1 0]  
 [0 1 0 1 0]  
 [0 1 0 1 0]]
```

In [322]:
def task_15_numpy(n):
    matrix = np.zeros((n, n), dtype=int)
    matrix[:, 1::2] = 1
    return matrix

def task_15_iterative(n):
    return [[0 if j % 2 == 0 else 1 for j in range(n)] for i in range(n)]

print(task_15_numpy(5))
print(np.array_equal(task_15_numpy(10), task_15_iterative(10)))

%timeit -n 100 -r 10 task_15_numpy(100)
%timeit -n 100 -r 10 task_15_iterative(100)

[[0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]
 [0 1 0 1 0]]
True
The slowest run took 4.37 times longer than the fastest. This could mean that an intermediate result is being cached.
5.57 µs ± 3.64 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
398 µs ± 14.3 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 17:


##### Fill array with values from 0 to n, replace all values less than n/2 and greater than 3n/4 with their opposites  
10  
[ 0 -1 -2 -3 -4 5 6 7 -8 -9 -10]

In [323]:
def task_17_numpy(n):
    array = np.arange(n+1)
    array[:math.ceil(n/2)] *= -1
    array[math.ceil(3*n/4):] *= -1
    return array

def task_17_iterative(n):
    return [-i if (i < n/2 or i > 3*n/4) else i for i in range(n + 1)]

print(task_17_numpy(10))
print(np.array_equal(task_17_numpy(37), task_17_iterative(37)))

%timeit -n 100 -r 10 task_17_numpy(133)
%timeit -n 100 -r 10 task_17_iterative(133)

[  0  -1  -2  -3  -4   5   6   7  -8  -9 -10]
True
4.55 µs ± 2.12 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
13 µs ± 1.12 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


## 18:


##### Generate array of n random numbers in range [0, 99], calculate number of unique numbers in sequence  
30  
In sequence [ 5 77 15 21 8 44 58 77 6 49 35 35 25 3 51 65 73 81 67 78 85 68 40 77 58 1 10 9 59 13] - 26 unique numbers

In [324]:
def task_18_numpy(n):
    return len(np.unique(np.random.randint(0, 100, n)))

def task_18_iterative(n):
    return len(set([random.randrange(0, 100) for i in range(n)]))  

print(task_18_numpy(30))

%timeit -n 100 -r 10 task_18_numpy(200)
%timeit -n 100 -r 10 task_18_iterative(200)

23
19.8 µs ± 3.56 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
80.5 µs ± 2.64 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)


# Task 2


#### Solving system of linear equations with Cramer's rule
___
**System**:
$$
\begin{cases}
 x_1 + 5x_2 + 3x_3 - 4x_4 = 20 \\
3x_1 +  x_2 - 2x_3        = 9 \\
5x_1 - 7x_2 +       10x_4 = -9 \\
       3x_2 - 5x_3        = 1
\end{cases}
$$

Check afterwards, using:
* matrix multiplication
* inverse matrix
* function ```numpy.linalg.solve()```

In [325]:
matrix = np.array([[1,  5,  3, -4],
                   [3,  1, -2,  0],
                   [5, -7,  0, 10],
                   [0,  3, -5,  0]])

results = np.array([20, 9, -9, 1])


def cramer(matrix, results):
    det = np.linalg.det(matrix)
    size = matrix.shape[0]
    
    if np.allclose(det, 0):
        print("Determinant is zero, aborting.")
        return solution
    
    solution = np.zeros(size)
    
    for i in range(size):
        temp_matrix = np.copy(matrix)
        temp_matrix[:, i] = np.copy(results)
        solution[i] = np.linalg.det(temp_matrix) / det   
    
    return solution
  
    
solution_cramer = cramer(matrix, results)
print(f"Naive result: {solution_cramer}") 

solution_numpy = np.linalg.solve(matrix, results)
print(f"NumPy result: {solution_numpy}\n")
assert np.allclose(solution_numpy, solution_cramer)

check_mult = np.dot(matrix, solution_cramer)
print("Check with matrix multiplication: ")
print(f"Expected value {results}")
print(f"Got value {check_mult}\n")
assert np.allclose(results, check_mult)

check_inv = np.dot(np.linalg.inv(matrix), results)
print("Check with inverse matrix: ")
print(f"Expected value {check_inv}")
print(f"Got value {solution_cramer}\n")
assert np.allclose(check_inv, solution_cramer)

Naive result: [ 3.  2.  1. -1.]
NumPy result: [ 3.  2.  1. -1.]

Check with matrix multiplication: 
Expected value [20  9 -9  1]
Got value [20.  9. -9.  1.]

Check with inverse matrix: 
Expected value [ 3.  2.  1. -1.]
Got value [ 3.  2.  1. -1.]



# Task 3


#### Evaluating matrix expression
___
Expression: $(A - B^2)(2A + B)$,

where 
$$
A =
\begin{pmatrix}
 5 & 2 & 0 \\
10 & 4 & 1 \\
 7 & 3 & 2
\end{pmatrix},
B = 
\begin{pmatrix}
 3 &  6 & -1 \\
-1 & -2 &  0 \\
 2 &  1 &  3
\end{pmatrix}
$$

Evaluate, using:
* NumPy functions
* iterative constructions (cycles, lists inclusions etc.)

For both versions calculate time and draw conclusions.

In [341]:
A = [[ 5, 2, 0],
     [10, 4, 1],
     [ 7, 3, 2]]

A_np = np.array(A)

B = [[ 3,  6, -1],
     [-1, -2,  0],
     [ 2,  1,  3]]

B_np = np.array(B)

def mmult(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_cols != b_rows:
        print("Wrong dimensions, multiplication is impossible.")
        return []
    
    return [[sum([x*y for (x, y) in zip(row, col)]) for col in zip(*B)] for row in A]
    
def madd(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_rows != b_rows or a_cols != b_cols:
        print("Wrong dimensions, addition is impossible.")
        return []

    return [[A[i][j] + B[i][j] for j in range(a_cols)] for i in range(a_rows)]

def msub(A, B):
    a_rows, a_cols = len(A), len(A[0])
    b_rows, b_cols = len(B), len(B[0])
    if a_rows != b_rows or a_cols != b_cols:
        print("Wrong dimensions, addition is impossible.")
        return []

    return [[A[i][j] - B[i][j] for j in range(a_cols)] for i in range(a_rows)]

def smult(scalar, matrix):
    rows, cols = len(matrix), len(matrix[0])
    return [[matrix[i][j] * scalar for j in range(cols)] for i in range(rows)]

def solve_numpy():
    return (A_np - B_np @ B_np) @ (2 * A_np + B_np)

def solve_iterative():
    return mmult(msub(A, mmult(B, B)), madd(smult(2, A), B))

print("Profiling:")
%timeit -n 100 -r 10 solve_numpy()
%timeit -n 100 -r 10 solve_iterative()

result_numpy = solve_numpy()
result_iterative = solve_iterative()

print("NumPy: ", result_numpy)
print("Iterative: ", result_iterative)
print("Equal: ", np.allclose(result_numpy, result_iterative))

Profiling:
3.43 µs ± 296 ns per loop (mean ± std. dev. of 10 runs, 100 loops each)
15.8 µs ± 2.88 µs per loop (mean ± std. dev. of 10 runs, 100 loops each)
NumPy:  [[  91   64   32]
 [ 257  146    1]
 [-322 -135  -51]]
Iterative:  [[91, 64, 32], [257, 146, 1], [-322, -135, -51]]
Equal:  True
